# Change HTTP port
quarkus.http.port=8180

# MySQL datasource configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=pratham
quarkus.datasource.password=pratham
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ecomm_db
#quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ecommerce_db

# Hibernate ORM configuration
quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.log.sql=true



# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,no-auth
#quarkus.http.cors.exposed-headers=location
quarkus.http.cors.access-control-allow-credentials=true


quarkus.http.auth.permission.cors.paths=/*
quarkus.http.auth.permission.cors.policy=permit




# --- OIDC Keycloak ---
quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=ecommerce-frontend
quarkus.oidc.application-type=service
quarkus.oidc.role-claim-path=realm_access.roles

quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.roles.source=accesstoken

#Mail Server
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.from=customer-support@ecommerce.org.in
quarkus.mailer.mock=false





#quarkus.log.level=DEBUG
#quarkus.log.console.level=DEBUG






##Define public endpoints
#quarkus.http.auth.permission.public.paths=/authenticate,/registerNewUser,/getAllProducts,/getProductDetailsById/*
#quarkus.http.auth.permission.public.policy=permit
## Define authenticated endpoints
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated













## PostgreSQL connection
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=root
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db
#
## Hibernate settings
#quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.log.sql=true


